// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6HZ0JHMuv-CRdJSd4nVoXY0Nbr1M4-rw',
    appId: '1:209556471108:web:a5fccaa378ac04d3586b11',
    messagingSenderId: '209556471108',
    projectId: 'todo-app-c11-34fcd',
    authDomain: 'todo-app-c11-34fcd.firebaseapp.com',
    storageBucket: 'todo-app-c11-34fcd.appspot.com',
    measurementId: 'G-9JM5GY9V61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAb-uPXeCR60JfDH7gqfmMGYdowF9QdRg',
    appId: '1:209556471108:android:9e81ad00f7183e6d586b11',
    messagingSenderId: '209556471108',
    projectId: 'todo-app-c11-34fcd',
    storageBucket: 'todo-app-c11-34fcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEiDbc6wkwzZvIm9LsEYEv1Mb_6HyIV00',
    appId: '1:209556471108:ios:57e44994d29beb09586b11',
    messagingSenderId: '209556471108',
    projectId: 'todo-app-c11-34fcd',
    storageBucket: 'todo-app-c11-34fcd.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEiDbc6wkwzZvIm9LsEYEv1Mb_6HyIV00',
    appId: '1:209556471108:ios:57e44994d29beb09586b11',
    messagingSenderId: '209556471108',
    projectId: 'todo-app-c11-34fcd',
    storageBucket: 'todo-app-c11-34fcd.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6HZ0JHMuv-CRdJSd4nVoXY0Nbr1M4-rw',
    appId: '1:209556471108:web:8c58b02724df39ee586b11',
    messagingSenderId: '209556471108',
    projectId: 'todo-app-c11-34fcd',
    authDomain: 'todo-app-c11-34fcd.firebaseapp.com',
    storageBucket: 'todo-app-c11-34fcd.appspot.com',
    measurementId: 'G-78DEVKNM0J',
  );

}